### ISSUE TITLE
Unsupported Date formats

### ISSUE THREAD

**Issue by manuelroth** [nzzdev/Q-chart#55]
Problem:
- Currently it is possible to add data with the date-field in the format ("MM JJ")
- Examples: Jan 17, Aug 18
- But according to the [Handbuch](https://wiki.nzzmg.ch/confluence/pages/viewpage.action?pageId=63343361&preview=/https%3A%2F%2Flh5.googleusercontent.com%2FwBoaJVhzdMw0vfllHx2uRROMNCiG-zyrqSfls8PqOU6EMT3UHLHbnrgJUfVt4yF0QzXlNzlFFan18O7l7rgo7c4VpocShT30WEuOAeI5L-zIxF-Qu6VY0HW5Aonfwoyt8-jWdEqV#HandbuchToolboxQ-EinneuesDiagrammerstellen) this format is not support
- I created a q-item on staging. So we can reproduce the issue: https://q.st-staging.nzz.ch/item/fd95b48105653a741171a56439bf32fb
- The chart gets displayed correctly, but the date-options are not available

Question:
- Is this behaviour intentional?

**Comment by benib** [comment]
@manuelroth yes this is intentional. If the date format is not recognised, we do not treat it as a date (the axis is not based on a time scale), we do not show the prognosis options etc.

but we still just render the line chart with a categorical scale.
