### ISSUE TITLE
Arrow Chart: implement "Invert color scheme" option

### ISSUE THREAD

**Issue by benib** [nzzdev/Q-chart#95]
## Current
Currently there is the expert option to pick the color scheme for arrow charts. There are 3 schemes available.

<img width="308" alt="screen shot 2018-09-28 at 10 13 11" src="https://user-images.githubusercontent.com/821875/46196537-b0036500-c307-11e8-8976-640a13c37b26.png">

## Todo
We need an additional Option to invert the scheme as there are cases where a transition to a lower value has a positive meaning and vice-versa.

This option should be place below the existing `colorScheme` option in `arrowOptions` (https://github.com/nzzdev/Q-chart/blob/dev/resources/schema.json#L520), be named `invertColorScheme` and be available to all users.

If checked (default `false`) the color scheme arrays need to be reversed before rendering.

**Comment by dnlbln** [comment]
done in [v3.7.6](https://github.com/nzzdev/Q-chart/releases/tag/v3.7.6)
